/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as OrganizerRouteImport } from './routes/_organizer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated.orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated.tickets'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin.admin.audit'
import { Route as AdminAdminCheckInRouteImport } from './routes/_admin.admin.check-in'
import { Route as AdminAdminEventsRouteImport } from './routes/_admin.admin.events'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin.admin.payments'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as OrganizerOrganizerCheckInRouteImport } from './routes/_organizer.organizer.check-in'
import { Route as OrganizerOrganizerEventsIndexRouteImport } from './routes/_organizer.organizer.events.index'
import { Route as OrganizerOrganizerEventsNewRouteImport } from './routes/_organizer.organizer.events.new'
import { Route as OrganizerOrganizerEventsEventIdImagesRouteImport } from './routes/_organizer.organizer.events.$eventId.images'
import { Route as OrganizerOrganizerEventsEventIdSalesRouteImport } from './routes/_organizer.organizer.events.$eventId.sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/_organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCheckInRoute = AdminAdminCheckInRouteImport.update({
  id: '/admin/check-in',
  path: '/admin/check-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEventsRoute = AdminAdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const OrganizerOrganizerCheckInRoute =
  OrganizerOrganizerCheckInRouteImport.update({
    id: '/organizer/check-in',
    path: '/organizer/check-in',
    getParentRoute: () => OrganizerRoute,
  } as any)
const OrganizerOrganizerEventsIndexRoute =
  OrganizerOrganizerEventsIndexRouteImport.update({
    id: '/organizer/events/',
    path: '/organizer/events/',
    getParentRoute: () => OrganizerRoute,
  } as any)
const OrganizerOrganizerEventsNewRoute =
  OrganizerOrganizerEventsNewRouteImport.update({
    id: '/organizer/events/new',
    path: '/organizer/events/new',
    getParentRoute: () => OrganizerRoute,
  } as any)
const OrganizerOrganizerEventsEventIdImagesRoute =
  OrganizerOrganizerEventsEventIdImagesRouteImport.update({
    id: '/organizer/events/$eventId/images',
    path: '/organizer/events/$eventId/images',
    getParentRoute: () => OrganizerRoute,
  } as any)
const OrganizerOrganizerEventsEventIdSalesRoute =
  OrganizerOrganizerEventsEventIdSalesRouteImport.update({
    id: '/organizer/events/$eventId/sales',
    path: '/organizer/events/$eventId/sales',
    getParentRoute: () => OrganizerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/check-in': typeof AdminAdminCheckInRoute
  '/admin/events': typeof AdminAdminEventsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/organizer/check-in': typeof OrganizerOrganizerCheckInRoute
  '/organizer/events/new': typeof OrganizerOrganizerEventsNewRoute
  '/organizer/events/': typeof OrganizerOrganizerEventsIndexRoute
  '/organizer/events/$eventId/images': typeof OrganizerOrganizerEventsEventIdImagesRoute
  '/organizer/events/$eventId/sales': typeof OrganizerOrganizerEventsEventIdSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events': typeof EventsIndexRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/check-in': typeof AdminAdminCheckInRoute
  '/admin/events': typeof AdminAdminEventsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/organizer/check-in': typeof OrganizerOrganizerCheckInRoute
  '/organizer/events/new': typeof OrganizerOrganizerEventsNewRoute
  '/organizer/events': typeof OrganizerOrganizerEventsIndexRoute
  '/organizer/events/$eventId/images': typeof OrganizerOrganizerEventsEventIdImagesRoute
  '/organizer/events/$eventId/sales': typeof OrganizerOrganizerEventsEventIdSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_organizer': typeof OrganizerRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/check-in': typeof AdminAdminCheckInRoute
  '/_admin/admin/events': typeof AdminAdminEventsRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_organizer/organizer/check-in': typeof OrganizerOrganizerCheckInRoute
  '/_organizer/organizer/events/new': typeof OrganizerOrganizerEventsNewRoute
  '/_organizer/organizer/events/': typeof OrganizerOrganizerEventsIndexRoute
  '/_organizer/organizer/events/$eventId/images': typeof OrganizerOrganizerEventsEventIdImagesRoute
  '/_organizer/organizer/events/$eventId/sales': typeof OrganizerOrganizerEventsEventIdSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orders'
    | '/profile'
    | '/tickets'
    | '/events/$eventId'
    | '/events/'
    | '/admin/audit'
    | '/admin/check-in'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/users'
    | '/organizer/check-in'
    | '/organizer/events/new'
    | '/organizer/events/'
    | '/organizer/events/$eventId/images'
    | '/organizer/events/$eventId/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/orders'
    | '/profile'
    | '/tickets'
    | '/events/$eventId'
    | '/events'
    | '/admin/audit'
    | '/admin/check-in'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/users'
    | '/organizer/check-in'
    | '/organizer/events/new'
    | '/organizer/events'
    | '/organizer/events/$eventId/images'
    | '/organizer/events/$eventId/sales'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_organizer'
    | '/login'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/tickets'
    | '/events/$eventId'
    | '/events/'
    | '/_admin/admin/audit'
    | '/_admin/admin/check-in'
    | '/_admin/admin/events'
    | '/_admin/admin/payments'
    | '/_admin/admin/users'
    | '/_organizer/organizer/check-in'
    | '/_organizer/organizer/events/new'
    | '/_organizer/organizer/events/'
    | '/_organizer/organizer/events/$eventId/images'
    | '/_organizer/organizer/events/$eventId/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OrganizerRoute: typeof OrganizerRouteWithChildren
  LoginRoute: typeof LoginRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer': {
      id: '/_organizer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/check-in': {
      id: '/_admin/admin/check-in'
      path: '/admin/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminAdminCheckInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/events': {
      id: '/_admin/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_organizer/organizer/check-in': {
      id: '/_organizer/organizer/check-in'
      path: '/organizer/check-in'
      fullPath: '/organizer/check-in'
      preLoaderRoute: typeof OrganizerOrganizerCheckInRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/organizer/events/': {
      id: '/_organizer/organizer/events/'
      path: '/organizer/events'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof OrganizerOrganizerEventsIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/organizer/events/new': {
      id: '/_organizer/organizer/events/new'
      path: '/organizer/events/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof OrganizerOrganizerEventsNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/organizer/events/$eventId/images': {
      id: '/_organizer/organizer/events/$eventId/images'
      path: '/organizer/events/$eventId/images'
      fullPath: '/organizer/events/$eventId/images'
      preLoaderRoute: typeof OrganizerOrganizerEventsEventIdImagesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/organizer/events/$eventId/sales': {
      id: '/_organizer/organizer/events/$eventId/sales'
      path: '/organizer/events/$eventId/sales'
      fullPath: '/organizer/events/$eventId/sales'
      preLoaderRoute: typeof OrganizerOrganizerEventsEventIdSalesRouteImport
      parentRoute: typeof OrganizerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminCheckInRoute: typeof AdminAdminCheckInRoute
  AdminAdminEventsRoute: typeof AdminAdminEventsRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminCheckInRoute: AdminAdminCheckInRoute,
  AdminAdminEventsRoute: AdminAdminEventsRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OrganizerRouteChildren {
  OrganizerOrganizerCheckInRoute: typeof OrganizerOrganizerCheckInRoute
  OrganizerOrganizerEventsNewRoute: typeof OrganizerOrganizerEventsNewRoute
  OrganizerOrganizerEventsIndexRoute: typeof OrganizerOrganizerEventsIndexRoute
  OrganizerOrganizerEventsEventIdImagesRoute: typeof OrganizerOrganizerEventsEventIdImagesRoute
  OrganizerOrganizerEventsEventIdSalesRoute: typeof OrganizerOrganizerEventsEventIdSalesRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerOrganizerCheckInRoute: OrganizerOrganizerCheckInRoute,
  OrganizerOrganizerEventsNewRoute: OrganizerOrganizerEventsNewRoute,
  OrganizerOrganizerEventsIndexRoute: OrganizerOrganizerEventsIndexRoute,
  OrganizerOrganizerEventsEventIdImagesRoute:
    OrganizerOrganizerEventsEventIdImagesRoute,
  OrganizerOrganizerEventsEventIdSalesRoute:
    OrganizerOrganizerEventsEventIdSalesRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OrganizerRoute: OrganizerRouteWithChildren,
  LoginRoute: LoginRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
