apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventide
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: eventide
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range $name, $svc := .Values.services }}
          {{- range $svc.ingressPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: 80
          {{- end }}
          {{- end }}
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
