import { defineConfig } from 'drizzle-kit'

// Emits SQL migration files for `auth_db`.
//
// The SCHEMA (`src/auth/schema.ts`) is GENERATED by the better-auth CLI from
// `apps/auth`'s config — never hand-edit it (CLAUDE.md, SYSTEM-DESIGN §4.2).
// Regenerate with `bun run --filter @eventide/auth generate:auth-schema`, then
// `bun run --filter @eventide/db generate:auth` to diff it into SQL.
//
// drizzle-kit only turns that schema into SQL and applies it, exactly as for the
// other two services. `migrate` reads DATABASE_URL from the environment and is
// run in-cluster by the bootstrap Job (§7.1), never from a laptop — RDS is not
// reachable from outside the VPC.
export default defineConfig({
  dialect: 'postgresql',
  schema: './src/auth/schema.ts',
  out: './migrations/auth',
  dbCredentials: { url: process.env.DATABASE_URL! },
})
