import * as schema from '@eventide/db/auth'
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { env } from '../env.ts'

/**
 * Drizzle instance over `auth_db`, passed to better-auth's Drizzle adapter.
 *
 * postgres.js is lazy — no socket is opened until the first query — so importing
 * this module from a unit test or the better-auth CLI does not require a running
 * database. `schema` comes from `packages/db/src/auth/schema.ts`, which is
 * generated by the better-auth CLI (SYSTEM-DESIGN §4.2).
 */
const client = postgres(env.DATABASE_URL, { max: 10 })

export const db = drizzle(client, { schema })
